vich_uploader:
  db_driver: orm

  metadata:
    type: annotation

  mappings:
    spice_images:
      uri_prefix: '%spice_images%'
      upload_destination: '%kernel.project_dir%/public%spice_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false