<?php

declare(strict_types=1);

namespace App\DataFixtures;

use App\Entity\Achievement;
use App\Entity\AromaticGroups;
use App\Enum\AchievementRarity;
use App\Enum\AchievementTrigger;
use App\Enum\GameMode;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AchievementFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $achievements = [
            [
                'slug' => 'discovery_1',
                'name' => 'Première Découverte',
                'description' => 'Consultez votre première fiche d\'épice.',
                'icon' => 'fa-solid fa-compass',
                'trigger' => AchievementTrigger::FIRST_DISCOVERY,
                'triggerValue' => 1,
                'xpReward' => 15,
                'rarity' => AchievementRarity::COMMON,
            ],
            [
                'slug' => 'first_game',
                'name' => 'Premier Quiz',
                'description' => 'Termine ton premier quiz éducatif',
                'icon' => 'fa-solid fa-graduation-cap',
                'trigger' => AchievementTrigger::FIRST_GAME,
                'triggerValue' => 1,
                'xpReward' => 15,
                'rarity' => AchievementRarity::COMMON,
            ],
            [
                'slug' => 'first_match',
                'name' => 'Première Alchimie',
                'description' => 'Créez votre tout premier mélange d\'épices.',
                'icon' => 'fa-solid fa-flask',
                'trigger' => AchievementTrigger::FIRST_MATCH,
                'triggerValue' => 1,
                'xpReward' => 15,
                'rarity' => AchievementRarity::COMMON,
            ],
            [
                'slug' => 'favorites_1',
                'name' => 'Premier Coup de Cœur',
                'description' => 'Ajoutez votre premier mélange à vos favoris.',
                'icon' => 'fa-solid fa-star',
                'trigger' => AchievementTrigger::N_FAVORITES,
                'triggerValue' => 1,
                'xpReward' => 15,
                'rarity' => AchievementRarity::COMMON,
            ],
            [
                'slug' => 'matches_5',
                'name' => 'Apprenti Alchimiste',
                'description' => 'Réalisez 5 mélanges d\'épices.',
                'icon' => 'fa-solid fa-mortar-pestle',
                'trigger' => AchievementTrigger::N_MATCHES,
                'triggerValue' => 5,
                'xpReward' => 25,
                'rarity' => AchievementRarity::COMMON,
            ],
            [
                'slug' => 'spices_3',
                'name' => 'Curieux',
                'description' => 'Combinez 3 épices différentes dans un même mélange.',
                'icon' => 'fa-solid fa-seedling',
                'trigger' => AchievementTrigger::N_SPICES_USED,
                'triggerValue' => 3,
                'xpReward' => 25,
                'rarity' => AchievementRarity::COMMON,
            ],
            [
                'slug' => 'spice_read_10',
                'name' => 'Lecteur Curieux',
                'description' => 'Consultez 10 fiches.',
                'icon' => 'fa-solid fa-book',
                'trigger' => AchievementTrigger::SPICE_READ,
                'triggerValue' => 10,
                'xpReward' => 25,
                'rarity' => AchievementRarity::COMMON,
            ],
            [
                'slug' => 'easter_egg_first',
                'name' => 'Œil de Lynx',
                'description' => 'Découvrez votre premier secret caché.',
                'icon' => 'fa-solid fa-egg',
                'trigger' => AchievementTrigger::EASTER_EGG_FOUND,
                'triggerValue' => 0,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
                'easterEggSlug' => 'first_egg',
            ],
            [
                'slug' => 'egg_alchimiste_de_l_ombre',
                'name' => 'Alchimiste de l\'Ombre',
                'description' => 'Maîtrise totale de la lumière et de l\'obscurité.',
                'icon' => 'fa-solid fa-moon',
                'trigger' => AchievementTrigger::EASTER_EGG_FOUND,
                'triggerValue' => 1,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
                'easterEggSlug' => 'alchimiste_de_l_ombre',
            ],
            [
                'slug' => 'egg_equilibre_des_contraires',
                'name' => 'Équilibre des Contraires',
                'description' => 'Le feu et la glace réunis dans un prisme.',
                'icon' => 'fa-solid fa-yin-yang',
                'trigger' => AchievementTrigger::EASTER_EGG_FOUND,
                'triggerValue' => 1,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
                'easterEggSlug' => 'equilibre_des_contraires',
            ],
            [
                'slug' => 'egg_grain_de_sel',
                'name' => 'Grain de Sel',
                'description' => 'Vous avez trouvé l\'icône cachée du footer !',
                'icon' => 'fa-solid fa-jar',
                'trigger' => AchievementTrigger::EASTER_EGG_FOUND,
                'triggerValue' => 1,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
                'easterEggSlug' => 'grain_de_sel',
            ],
            [
                'slug' => 'egg_la_recette_perdue',
                'name' => 'La Recette Perdue',
                'description' => 'Les 4 mots sacrés ont été réunis.',
                'icon' => 'fa-solid fa-key',
                'trigger' => AchievementTrigger::EASTER_EGG_FOUND,
                'triggerValue' => 1,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
                'easterEggSlug' => 'la_recette_perdue',
            ],
            [
                'slug' => 'egg_le_poids_de_l_or',
                'name' => 'Le Poids de l\'Or',
                'description' => 'Vous avez trouvé la valeur du Poivre Noir.',
                'icon' => 'fa-solid fa-coins',
                'trigger' => AchievementTrigger::EASTER_EGG_FOUND,
                'triggerValue' => 1,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
                'easterEggSlug' => 'le_poids_de_l_or',
            ],
            [
                'slug' => 'egg_perdu_dans_le_souk',
                'name' => 'Perdu dans le Souk',
                'description' => 'Même perdu, vous avez su garder votre calme.',
                'icon' => 'fa-solid fa-map-signs',
                'trigger' => AchievementTrigger::EASTER_EGG_FOUND,
                'triggerValue' => 1,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
                'easterEggSlug' => 'perdu_dans_le_souk',
            ],
            [
                'slug' => 'egg_secret_du_curry',
                'name' => 'Secret du Curry',
                'description' => 'La sainte trinité : Curcuma, Cumin, Gingembre.',
                'icon' => 'fa-solid fa-scroll',
                'trigger' => AchievementTrigger::EASTER_EGG_FOUND,
                'triggerValue' => 1,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
                'easterEggSlug' => 'secret_du_curry',
            ],
            [
                'slug' => 'egg_temps_de_l_infusion',
                'name' => 'Temps de l\'Infusion',
                'description' => 'La patience est la clé d\'un bon mélange (4:20).',
                'icon' => 'fa-solid fa-hourglass-end',
                'trigger' => AchievementTrigger::EASTER_EGG_FOUND,
                'triggerValue' => 1,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
                'easterEggSlug' => 'temps_de_l_infusion',
            ],
            [
                'slug' => 'discovery_10',
                'name' => 'Explorateur',
                'description' => 'Découvrez 10 épices différentes.',
                'icon' => 'fa-solid fa-map',
                'trigger' => AchievementTrigger::FIRST_DISCOVERY,
                'triggerValue' => 10,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
            ],
            [
                'slug' => 'favorites_5',
                'name' => 'Collectionneur d\'Arômes',
                'description' => 'Ajoutez 5 mélanges à vos favoris.',
                'icon' => 'fa-solid fa-bookmark',
                'trigger' => AchievementTrigger::N_FAVORITES,
                'triggerValue' => 5,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
            ],
            [
                'slug' => 'games_10',
                'name' => 'Étudiant Assidu',
                'description' => 'Termine 10 quiz éducatifs',
                'icon' => 'fa-solid fa-school',
                'trigger' => AchievementTrigger::N_GAMES_COMPLETED,
                'triggerValue' => 10,
                'xpReward' => 50,
                'rarity' => AchievementRarity::RARE,
            ],
            [
                'slug' => 'matches_10',
                'name' => 'Alchimiste',
                'description' => 'Réalisez 10 mélanges d\'épices.',
                'icon' => 'fa-solid fa-fire',
                'trigger' => AchievementTrigger::N_MATCHES,
                'triggerValue' => 10,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
            ],
            [
                'slug' => 'spices_5',
                'name' => 'Explorateur des Saveurs',
                'description' => 'Combinez 5 épices différentes dans un même mélange.',
                'icon' => 'fa-solid fa-compass',
                'trigger' => AchievementTrigger::N_SPICES_USED,
                'triggerValue' => 5,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
            ],
            [
                'slug' => 'streak_3',
                'name' => 'Assidu',
                'description' => '3 jours consécutifs de lecture.',
                'icon' => 'fa-solid fa-fire',
                'trigger' => AchievementTrigger::READING_STREAK,
                'triggerValue' => 3,
                'xpReward' => 30,
                'rarity' => AchievementRarity::RARE,
            ],
            [
                'slug' => 'spice_read_25',
                'name' => 'Botaniste en Herbe',
                'description' => 'Consultez 25 fiches d\'épices ou terpènes.',
                'icon' => 'fa-solid fa-seedling',
                'trigger' => AchievementTrigger::SPICE_READ,
                'triggerValue' => 25,
                'xpReward' => 35,
                'rarity' => AchievementRarity::RARE,
            ],
            [
                'slug' => 'discovery_30',
                'name' => 'Grand Explorateur',
                'description' => 'Découvrez 30 épices différentes.',
                'icon' => 'fa-solid fa-globe',
                'trigger' => AchievementTrigger::FIRST_DISCOVERY,
                'triggerValue' => 30,
                'xpReward' => 60,
                'rarity' => AchievementRarity::EPIC,
            ],
            [
                'slug' => 'favorites_10',
                'name' => 'Bibliothèque des Saveurs',
                'description' => 'Ajoutez 10 mélanges à vos favoris.',
                'icon' => 'fa-solid fa-book-open',
                'trigger' => AchievementTrigger::N_FAVORITES,
                'triggerValue' => 10,
                'xpReward' => 60,
                'rarity' => AchievementRarity::EPIC,
            ],
            [
                'slug' => 'games_50',
                'name' => 'Maître du Savoir',
                'description' => 'Termine 50 quiz éducatifs',
                'icon' => 'fa-solid fa-brain',
                'trigger' => AchievementTrigger::N_GAMES_COMPLETED,
                'triggerValue' => 50,
                'xpReward' => 100,
                'rarity' => AchievementRarity::EPIC,
            ],
            [
                'slug' => 'matches_25',
                'name' => 'Maître des Arômes',
                'description' => 'Réalisez 25 mélanges d\'épices.',
                'icon' => 'fa-solid fa-crown',
                'trigger' => AchievementTrigger::N_MATCHES,
                'triggerValue' => 25,
                'xpReward' => 65,
                'rarity' => AchievementRarity::EPIC,
            ],
            [
                'slug' => 'spices_8',
                'name' => 'Symphonie d\'Épices',
                'description' => 'Combinez 8 épices différentes dans un même mélange.',
                'icon' => 'fa-solid fa-music',
                'trigger' => AchievementTrigger::N_SPICES_USED,
                'triggerValue' => 8,
                'xpReward' => 60,
                'rarity' => AchievementRarity::EPIC,
            ],
            [
                'slug' => 'streak_7',
                'name' => 'Lecteur Assidu',
                'description' => '7 jours consécutifs de lecture.',
                'icon' => 'fa-solid fa-fire-flame-curved',
                'trigger' => AchievementTrigger::READING_STREAK,
                'triggerValue' => 7,
                'xpReward' => 60,
                'rarity' => AchievementRarity::EPIC,
            ],
            [
                'slug' => 'spice_read_50',
                'name' => 'Apprenti des Terpènes',
                'description' => 'Consultez 50 fiches d\'épices ou terpènes.',
                'icon' => 'fa-solid fa-book-open',
                'trigger' => AchievementTrigger::SPICE_READ,
                'triggerValue' => 50,
                'xpReward' => 65,
                'rarity' => AchievementRarity::EPIC,
            ],
            [
                'slug' => 'prisme_des_terpenes',
                'name' => 'Prisme des Terpènes',
                'description' => 'Explorez au moins une épice de chaque grande famille aromatique.',
                'icon' => 'fa-solid fa-gem',
                'trigger' => AchievementTrigger::ALL_TERPENES_VISITED,
                'triggerValue' => 1,
                'xpReward' => 125,
                'rarity' => AchievementRarity::LEGENDARY,
            ],
            [
                'slug' => 'easter_egg_all',
                'name' => 'Chasseur de Secrets',
                'description' => 'Découvrez tous les secrets cachés.',
                'icon' => 'fa-solid fa-magnifying-glass',
                'trigger' => AchievementTrigger::EASTER_EGG_FOUND,
                'triggerValue' => 0,
                'xpReward' => 150,
                'rarity' => AchievementRarity::LEGENDARY,
                'easterEggSlug' => 'all_eggs',
            ],
            [
                'slug' => 'games_100',
                'name' => 'Docteur ès Épices',
                'description' => 'Termine 100 quiz éducatifs',
                'icon' => 'fa-solid fa-award',
                'trigger' => AchievementTrigger::N_GAMES_COMPLETED,
                'triggerValue' => 100,
                'xpReward' => 200,
                'rarity' => AchievementRarity::LEGENDARY,
            ],
            [
                'slug' => 'matches_50',
                'name' => 'Grand Maître Alchimiste',
                'description' => 'Réalisez 50 mélanges d\'épices.',
                'icon' => 'fa-solid fa-star',
                'trigger' => AchievementTrigger::N_MATCHES,
                'triggerValue' => 50,
                'xpReward' => 125,
                'rarity' => AchievementRarity::LEGENDARY,
            ],
            [
                'slug' => 'puriste_100',
                'name' => 'Puriste',
                'description' => '100 mélanges réalisés.',
                'icon' => 'fa-solid fa-gem',
                'trigger' => AchievementTrigger::N_MATCHES,
                'triggerValue' => 100,
                'xpReward' => 200,
                'rarity' => AchievementRarity::LEGENDARY,
            ],
            [
                'slug' => 'streak_30',
                'name' => 'Moine des Épices',
                'description' => '30 jours consécutifs de lecture.',
                'icon' => 'fa-solid fa-fire-flame-simple',
                'trigger' => AchievementTrigger::READING_STREAK,
                'triggerValue' => 30,
                'xpReward' => 125,
                'rarity' => AchievementRarity::LEGENDARY,
            ],
            [
                'slug' => 'spice_read_100',
                'name' => 'Encyclopédiste',
                'description' => 'Consultez 100 fiches d\'épices ou terpènes.',
                'icon' => 'fa-solid fa-book-bookmark',
                'trigger' => AchievementTrigger::SPICE_READ,
                'triggerValue' => 100,
                'xpReward' => 125,
                'rarity' => AchievementRarity::LEGENDARY,
            ],
            [
                'slug' => 'game_perfect_qcm_3',
                'name' => 'Sans Faute',
                'description' => 'Terminez 3 QCM sans la moindre erreur.',
                'icon' => 'fa-solid fa-bullseye',
                'trigger' => AchievementTrigger::GAME_PERFECT_RUN,
                'triggerValue' => 3,
                'xpReward' => 40,
                'rarity' => AchievementRarity::RARE,
                'contextGameMode' => GameMode::QCM,
            ],
            [
                'slug' => 'game_score_chrono_50',
                'name' => 'Main Leste',
                'description' => 'Décrochez 50 XP sur une seule partie de Chrono.',
                'icon' => 'fa-solid fa-stopwatch',
                'trigger' => AchievementTrigger::GAME_SCORE_THRESHOLD,
                'triggerValue' => 50,
                'xpReward' => 40,
                'rarity' => AchievementRarity::RARE,
                'contextGameMode' => GameMode::CHRONO,
            ],
            [
                'slug' => 'group_mastery_capsaicinoides',
                'name' => 'Maître du Feu',
                'description' => 'Consultez toutes les épices des Capsaïcinoïdes & Alcaloïdes.',
                'icon' => 'fa-solid fa-pepper-hot',
                'trigger' => AchievementTrigger::GROUP_MASTERY_READ,
                'triggerValue' => 20,
                'xpReward' => 75,
                'rarity' => AchievementRarity::EPIC,
                'contextAromaticGroupSlug' => 'capsaicinoides-alcaloides',
            ],
            [
                'slug' => 'all_preparation_methods_read',
                'name' => 'Toutes Préparations',
                'description' => 'Découvrez chaque méthode de préparation au fil de vos lectures.',
                'icon' => 'fa-solid fa-mortar-pestle',
                'trigger' => AchievementTrigger::ALL_PREPARATION_METHODS_READ,
                'triggerValue' => 0,
                'xpReward' => 75,
                'rarity' => AchievementRarity::EPIC,
            ],
        ];

        $repository = $manager->getRepository(Achievement::class);
        $groupRepository = $manager->getRepository(AromaticGroups::class);

        foreach ($achievements as $data) {
            $achievement = $repository->findOneBy([
                'slug' => $data['slug'],
            ]) ?? new Achievement();

            $achievement->setSlug($data['slug'])
                ->setName($data['name'])
                ->setDescription($data['description'])
                ->setIcon($data['icon'])
                ->setTrigger($data['trigger'])
                ->setTriggerValue($data['triggerValue'])
                ->setXpReward($data['xpReward'])
                ->setRarity($data['rarity'])
                ->setEasterEggSlug($data['easterEggSlug'] ?? null)
                ->setContextGameMode($data['contextGameMode'] ?? null)
                ->setEnabled(true);

            if (isset($data['contextAromaticGroupSlug'])) {
                $achievement->setContextAromaticGroup($groupRepository->findOneBy([
                    'slug' => $data['contextAromaticGroupSlug'],
                ]));
            }

            $manager->persist($achievement);
            $this->addReference('achievement_' . $data['slug'], $achievement);
        }

        $manager->flush();
    }
}
